# Generated by Django 4.0.4 on 2022-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Описание вопроса')),
                ('type_question', models.CharField(choices=[('RN', 'Возврат'), ('WC', 'Гарантийный случай'), ('EX', 'Обмен'), ('RP', 'Ремонт')], default='ОК', max_length=2)),
                ('date_create', models.DateField()),
                ('application_status', models.CharField(choices=[('ОК', 'Обрабатывается'), ('ПР', 'Принято'), ('ОТ', 'Отказ')], default='RN', max_length=2)),
                ('date_change_status', models.DateField(auto_now=True)),
            ],
        ),
    ]
